Patch 1
frontend-park-mail-ru/2018_1_shark_team pull request #1
Opened 2018-02-22 22:50 UTC by 3kybika

2018-02-28 02:57 UTC, reo7sp requested changes

2018-02-28 02:57 UTC, reo7sp commented on .gitignore
> +.idea/
Да можно один раз написать `.idea`) Сработает и на файл, и на папку

2018-02-28 02:57 UTC, reo7sp commented on package.json
> +    "make-pug": "pug -c --extension 'pug.js' --name-after-file ./static",
Что-то не вижу, чтобы вы эти pug.js потом использовали 🤔

2018-02-28 02:57 UTC, reo7sp commented on package.json
> +    "make-es2015": "babel static/output/webpack_output -d static/output/babel_output --presets es2015",
# ❗️
Давайте сразу в вебпаке прогонять js через бабель) Вот через этот лоадер можно: https://github.com/babel/babel-loader

2018-02-28 02:57 UTC, reo7sp commented on static/index.html
> +<script src = "./output/babel_output/result.js"></script>
# ❗️ 
Кстати, странно, что у вас в папке static одновременно и исходные js, pug, и собранные js. 
Давайте лучше разнесем на две папки: `src` и `dist` – в первой исходники, во второй собранное. Копировать хтмлки и картинки можно плагином https://github.com/webpack-contrib/copy-webpack-plugin

2018-02-28 02:57 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +    static sendPost(url, body, callback) {
# ❗️ 
Мне не очень нравятся классы с одними только статическими методами.

Лучше:
- Сделать его методы нестатическими и прокидывать инстанс класса везде. 
Типа чтобы SOLIDно было https://en.wikipedia.org/wiki/Dependency_inversion_principle. Это поможет нам, например, при тестировании (ахахх, все равно заниматься ими не будем ж) подменить инстанс AjaxWorker каким-то фиксивным объектом, который не будет отправлять запросы к серверу.
- Или забить и просто превратить класс в несколько обычных функций.

2018-02-28 02:57 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +    static sendPost(url, body, callback) {
Если влом везде теперь пихать в конструкторы много таких параметров-зависимостей, то можно сделать класс _Service Locator_, в котором будут лежать ссылки на всякие нужные объекты. 

<br>

**Service Locator**

Что такое: https://martinfowler.com/articles/injection.html#UsingAServiceLocator

Короче, как пользоваться:
1. Создаем класс вида
    ```javascript
    class ServiceLocator {
        constructor() {
            this._api = new AjaxWorker(); 
            // либо сам сервис локатор может разбираться как создавать инстансы, как тут, 
            // либо можно поручить это отдельному классу/функции.
        }

        get api() {
            return this._api;
        }
    }
    ```
2. Используем
    ```javascript
    class Какойто {
        constructor(serviceLocator) {
            this._api = serviceLocator.api;  // заинжектили зависимость так
        }

        subscribeToEvents() {
            элемент.addEventListener('click', () => {
                this._api.тырыпыры();
            });
        }
    }
    ```

2018-02-28 02:57 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +        xhr.onreadystatechange = function() {
Давайте напишем стрелочную функцию

2018-02-28 02:57 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +                xhr = null;
Зачем xhr = null, эта строчка ведь ни на что не влияет 🤔

2018-02-28 02:57 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +        let xhr = new XMLHttpRequest();
Можно const, ведь ссылка не меняется

2018-02-28 02:57 UTC, reo7sp commented on static/modules/StringContentManager.js
> +    static normalChar(charParam) {
# ⚠️ 
Давайте сделаем эти две статические функции обычными функциями, без класса. У нас же тут не джава, всё проще))))

2018-02-28 02:57 UTC, reo7sp commented on static/views/log-in-page/LogInPage.js
> +        LogInPage.render();
# ❗️ 

Вот не нравится мне что что-то серьезное делается прям в конструторе.
Пусть лучше конструктор только соберет инстанс и всё. Рендер вызовем явно.
```js
const page = new LogInPage();
page.render();
```

2018-02-28 02:57 UTC, reo7sp commented on static/views/log-in-page/LogInPage.js
> +        document.querySelector(".center-box").innerHTML += template();
Зачем `+=`, а не просто `=`?)))

2018-02-28 02:57 UTC, reo7sp commented on static/views/log-in-page/LogInPage.js
> +            for(let i = 0; i < messageArr.length; i++) {
Давайте лучше воспользуемся `messageArr.forEach`

2018-02-28 02:57 UTC, reo7sp commented on static/views/log-in-page/LogInPage.js
> +
Покучнее бы эти 4 ифа, без пустых строк между ними. Типа одного смысла блоки кода.
Можете забить, это просто по кодстайлу коммент.

2018-02-28 02:57 UTC, reo7sp commented on static/views/log-in-page/log-in-page.scss
> +.log-in-page__form .form__login-input-field {
# ❗️ 

Ой не надо так. БЭМ как раз придуман против таких каскадных правил.

Используйте модификаторы, если формочка на логине должна выглядеть слегка по-другому, чем везде https://ru.bem.info/methodology/block-modification/

Типа:
```html
<input class="form__login-input-field form__login-input-field--log-in-page">
```
```css
.form__login-input-field {
    обычные правила для полей
}

.form__login-input-field--log-in-page {
    background-color: yellow; // о, а го в форме входа это поле будет желтым, ыыы
}
```

2018-02-28 02:57 UTC, reo7sp commented on static/views/main-menu-page/MainMenuPage.js
> +    static render() {
Ну зачем оно статическое

2018-02-28 02:57 UTC, reo7sp commented on static/views/main-menu-page/MainMenuPage.js
> +        MainMenuPage.render();
Не надо в конструкторе делать что-то серьезное

2018-02-28 02:57 UTC, reo7sp commented on static/views/sign-up-page/SignUpPage.js
> +            const login = elementsBase.getElement("signUpLoginField").value;
# ❗️ 

У вас как-то странно, что в этой функции вы часть элементов берете через `document.querySelector`, а часть из своего `elementsBase`)) Определитесь на чем-то одном)

2018-02-28 02:57 UTC, reo7sp commented on webpack.config.js
> +                        includePaths: ["absolute/path/a", "absolute/path/b"]
Можно убрать эту копипастную строчку)

2018-02-28 02:57 UTC, reo7sp commented on static/modules/Router.js
> +        for(let i = 0; i < this.listOfPages.length; i++) {
Давайте воспользуемся `forEach`

2018-02-28 02:57 UTC, reo7sp commented on static/modules/Router.js
> +        for(let i = 0; i < this.listOfPages.length; i++) {
# ⚠️ 

Ну и тут бы `forEach`

2018-02-28 02:57 UTC, reo7sp commented on static/modules/Start.js
> +    new Start();
# ❗️ 

Какой-то джавовский стиль, что ли, делать куча всего прям в конструкторе. Ну не надо так)
Лучше явно отдельно написать метод, который запустит приложение:
```js
const starter = new Start();
starter.initPage();
```

2018-02-28 02:57 UTC, reo7sp commented on static/modules/Start.js
> +        LogInPage.addEventsToElements(this.router, this.elementsBase);
Какая-то странная идея, я бы из render() вызывал этот addEventsToElements, регал события. Ну ладно

2018-03-09 15:00 UTC, maxim218 commented on package.json
> +    "make-pug": "pug -c --extension 'pug.js' --name-after-file ./static",
Используются при рендере

2018-03-09 15:01 UTC, maxim218 commented on package.json
> +    "make-es2015": "babel static/output/webpack_output -d static/output/babel_output --presets es2015",
Пока, думаю, не стоит перегружать вебпак
Это мы лучше понимаем как работает

2018-03-09 15:02 UTC, maxim218 commented on static/index.html
> +<script src = "./output/babel_output/result.js"></script>
У нас есть папка output===dist

2018-03-09 15:03 UTC, maxim218 commented on webpack.config.js
> +                        includePaths: ["absolute/path/a", "absolute/path/b"]
Без нее не работало

2018-03-09 15:16 UTC, maxim218 commented on static/modules/Router.js
> +        for(let i = 0; i < this.listOfPages.length; i++) {
Ок, поменял

2018-03-09 15:17 UTC, maxim218 commented on static/modules/Start.js
> +    new Start();
Мне в прошлый раз Дмитрий Дорофеев говорил, что если нет необходимости хранить имя экземпляра класса, то лучше этого не делать.

2018-03-09 17:35 UTC, reo7sp commented on .gitignore
> +.idea/
done

2018-03-09 17:39 UTC, reo7sp commented on package.json
> +    "make-pug": "pug -c --extension 'pug.js' --name-after-file ./static",
Нет, не используется. Вам pug-loader в вебпаке паг грузит.

На всякий случай я попробовал убрать вызов `npm run make-pug` из скрипта prestart в package.json и удалить сгенереренные эти .pug.js, чтобы понять, оторвет у меня сборку или нет. Не оторвало, все-таки из вебпака паг тянется.

2018-03-09 17:39 UTC, reo7sp commented on package.json
> +    "make-es2015": "babel static/output/webpack_output -d static/output/babel_output --presets es2015",
ok

2018-03-09 17:39 UTC, reo7sp commented on static/index.html
> +<script src = "./output/babel_output/result.js"></script>
ok

2018-03-09 17:42 UTC, reo7sp commented on webpack.config.js
> +                        includePaths: ["absolute/path/a", "absolute/path/b"]
Я попробовал сейчас сам убрать строки
 ```
options: {
    includePaths: ["absolute/path/a", "absolute/path/b"]
}
```
и у меня всё норм собралось

2018-03-09 17:42 UTC, reo7sp commented on static/modules/Router.js
> +        for(let i = 0; i < this.listOfPages.length; i++) {
done

2018-03-09 17:43 UTC, reo7sp commented on static/modules/Router.js
> +        for(let i = 0; i < this.listOfPages.length; i++) {
done

2018-03-09 19:05 UTC, reo7sp requested changes

2018-03-09 19:05 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +    constructor(url, body, callback) {
А какая идея за тем, чтобы делать так? Не понимаю, зачем усложнять и создавать новый объект AjaxWorker на каждый раз. Объясните плз.

Я бы вообще сделал так:

```js
// AjaxWorker.js

export default class AjaxWorker {
    constructor(baseUrl) {
        this.baseUrl = baseUrl;
    }

    sendPost(url, body, callback) {
        // ...
    }
}


// ServiceLocator.js

export default class ServiceLocator { // реализуем таким образом dependency injection
    constructor(ajaxWorker) {
        this.ajaxWorker = ajaxWorker;
    }
}


// Start.js

class Start {
    constructor() {
        this.createServiceLocator();
        // ...
    }

    createServiceLocator() {
        const ajaxBaseUrl = "http://localhost:5005/";
        const ajaxWorker = new AjaxWorker(ajaxBaseUrl);

        // в будущем ещё какие-то зависимости будут тут инициализоваться

        this.serviceLocator = new ServiceLocator(ajaxWorker);
    }

    createPages() {
        this.logInPage = new LogInPage(this.serviceLocator); // эти вьюхи уже берут инстанс ajaxWorker через сервис локатор
        this.signInPage = new SignUpPage(this.serviceLocator);
        this.mainMenuPage = new MainMenuPage(this.serviceLocator);
    }
}
```

2018-03-09 19:05 UTC, reo7sp commented on static/modules/Router.js
> +        let flag = true;
Можно было бы сделать проще
```js
let nextPage = this.listOfPages.find((p) => p.url === url);
if (!nextPage) {
    nextPage = this.listOfPages[0];
}
```

2018-03-09 19:05 UTC, reo7sp commented on static/modules/Router.js
>          this.listOfPages[0].page.hidden = false;
Ну эт прям костыль.
Сделайте отдельную норм функцию showDefaultPage(), которая бы как раз этот логин показывала на старте.

2018-03-09 19:05 UTC, reo7sp commented on static/modules/SignupFormValidator.js
> +        for(let i = 0; i < messageArr.length; i++) {
forEach

2018-03-09 19:05 UTC, reo7sp commented on static/modules/SignupFormValidator.js
> +            messageBox.appendChild(p);
Потом стоит разделить логику самой валидации, логику показывания ошибок и логику посылки запроса. У функции должна быть одна обязанность (см. S in SOLID)

2018-03-09 19:05 UTC, reo7sp commented on static/modules/SignupFormValidator.js
> +        if(new StringContentManager(login).normalString() === false) {
Вообще не понимаю, зачем так делать, а не обойтись обычной функцией. Обычной в смысле без класса, без всего, прям так. Объясните, плз

2018-03-09 19:05 UTC, reo7sp commented on static/modules/StringContentManager.js
> +        this.s = stringParam;
??? 
![](https://301-1.ru/important-memes/img/2015_12_13_12_12_08_182085436f7baa77bad8a6998a248417.jpg)

2018-03-09 19:41 UTC, reo7sp commented
Итак, давайте вот как решим с вебпаком и всякими моими загонами по поводу DI.
1. Вебпак пока уберем до начала второго модуля.
2. Будем запихивать содержимое наших текущих js файлов в IIFE-функции и писать ссылки на объекты/классы прям в window. Вот как тут делают ребята https://github.com/frontend-park-mail-ru/2018_1_tarados-feroces/blob/sandbox/src/app/modules/HttpModule/HttpModule.js.
3. Оставим генерацию .pug.js файлов. 
    - Как пользоваться ими: Паг в каждом из них генерирует функцию вида `имяФайлаКамельКейсомTemplate`. То есть:
        - внутри `log-in-page.pug.js` есть функция `logInPageTemplate`,
        - внутри `main-menu-page.pug.js` – `mainMenuPageTemplate`,
        - а внутри `sign-up-page.pug.js` – `signUpPageTemplate`.
4. Придется ещё и собирать sass через cli, да. https://www.npmjs.com/package/node-sass#command-line-interface
5. Разделите наконец папку static на src и dist. В src – исходники, в dist – то, что будете в index.html подключать.
5. Чтобы не маяться со вбиваением 100500 js и css файлов в index.html, давайте все файлы контактенировать обычными консольными утилитами. То есть так: `cat $(find src -type f -name "*.js") > dist/bundle.js`.

2018-03-09 20:02 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +        xhr.onreadystatechange = function() {
done

2018-03-09 20:02 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +                xhr = null;
?

2018-03-09 20:03 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +    static sendPost(url, body, callback) {
not resolved

2018-03-09 20:04 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +                xhr = null;
not resolved

2018-03-09 20:04 UTC, reo7sp commented on static/modules/AjaxWorker.js
> +        let xhr = new XMLHttpRequest();
not resolved

2018-03-09 20:04 UTC, reo7sp commented on static/views/log-in-page/LogInPage.js
> +        LogInPage.render();
not resolved

2018-03-09 20:04 UTC, reo7sp commented on static/modules/StringContentManager.js
> +    static normalChar(charParam) {
not resolved

2018-03-09 20:04 UTC, reo7sp commented on static/views/log-in-page/LogInPage.js
> +        document.querySelector(".center-box").innerHTML += template();
not resolved

2018-03-09 20:04 UTC, reo7sp commented on static/views/log-in-page/LogInPage.js
> +            for(let i = 0; i < messageArr.length; i++) {
not resolved

2018-03-09 20:05 UTC, reo7sp commented on static/views/log-in-page/log-in-page.scss
> +.log-in-page__form .form__login-input-field {
not resolved

2018-03-09 20:05 UTC, reo7sp commented on static/modules/Start.js
> +    new Start();
🤔🤔🤔

2018-03-10 11:42 UTC, reo7sp commented
Перемещено в #6

2018-03-10 11:42 UTC, closed without merging