Dev
frontend-park-mail-ru/2018_1_shark_team pull request #22
Opened 2018-05-21 01:55 UTC by maxim218

2018-05-21 01:56 UTC, maxim218 commented
Изменения в дизайне.
Далее сделаю медиа-запросы для отделения мобилок от ноутов =)

2018-05-21 12:18 UTC, reo7sp requested changes

2018-05-21 12:18 UTC, reo7sp commented on static/global.scss
> +    font-size: 3vw;
Вообще плохая идея размер шрифта относительно высоты экрана задавать, потому что непонятно что на мобилках будет. 😔 Лучше четко пикселях задавайте, как раньше делали. 

_**ПОДСКАЗКА**_ 🐶🐶🐶: добавьте в index.html в \<head\> строчку `<meta name="viewport" content="width=device-width, initial-scale=1">`. Она делает на мобилках всё хорошо, то есть не придется специально увеличивать размер шрифта через css.

2018-05-21 12:18 UTC, reo7sp commented on static/global.scss
> +    img {
Тут призабыли про таск от Толи🐝:
> нельзя использовать вложенные селекторы .a .b .c
https://github.com/frontend-park-mail-ru/2018_1_shark_team/issues/20

2018-05-21 12:18 UTC, reo7sp commented on static/views/liders-page/liders-page.scss
> +  @extend .button-field;
Призабыли про таск от Толи🐝:
> настройте линтинг стилей 
https://github.com/frontend-park-mail-ru/2018_1_shark_team/issues/20

Тут почему-то отступ в два пробела, хотя везде 4. Линтер бы подчеркнул.

2018-05-21 19:18 UTC, reo7sp approved these changes

2018-05-22 01:01 UTC, reo7sp approved these changes

2018-05-22 01:09 UTC, merged